export const CONNECTIONS_LOADED_SUCCESSFULLY =
  'CONNECTIONS_LOADED_SUCCESSFULLY';
export const ERROR_CONNECTIONS_LOADING = 'ERROR_CONNECTIONS_LOADING';
export const SEARCH_VALUE_CHANGED = 'SEARCH_VALUE_CHANGED';
export const TEXTINPUT_FOCUSED = 'TEXTINPUT_FOCUSED';
export const TEXTINPUT_BLURRED = 'TEXTINPUT_BLURRED';
export const SORT_ASCENDING = 'SORT_ASCENDING';
export const SORT_DESCENDING = 'SORT_DESCENDING';
export const SORT_NONE = 'SORT_NONE';
